In [1]:
import pandas as pd 
import numpy as np

In [16]:
data = {
    "Name": ["A", "B", "A", "C"],
    "Age": [20, 21, 20, 22]
}

df = pd.DataFrame( data )

print( df.duplicated( subset=['Name']))

df.drop_duplicates( subset=['Name'] , inplace=True )

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
print( df.duplicated( ))

0    False
1    False
3    False
dtype: bool

In [18]:
import pandas as pd 
data = {
    't_id' : [ 1,1,1,2,2,2,2] ,
    's_id' : [2,2,3,1,2,3,4] ,
    'd_id' : [3,4,3,1,1,1,1]
}

df = pd.DataFrame( data )

df = df.drop_duplicates(subset=['t_id','s_id'])
df = df.groupby('t_id').size().reset_index().rename(columns={-1: 'count'})
df

   t_id  0
0     1  2
1     2  4

In [7]:
import pandas as pd 

data = {
    "name": ["A", "B", "C", "D"],
    "marks": [85, 92, 78, 92]
}


df = pd.DataFrame( data ) 
df = df.sort_values(by="marks", ascending=False)
df['rank'] = df['marks'].rank( ascending=False , method="dense")
df

  name  marks  rank
1    B     92   1.0
3    D     92   1.0
0    A     85   2.0
2    C     78   3.0